name: Pull request labeler

on: [ pull_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@cf194d0d38687763391882d1fa7ca3d690ff0e4c
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
