on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: make test

